In [19]:
!pip install pyperclip
import pandas as pd
import os
import json
import pyperclip

Requirement already satisfied: pyperclip in /Users/bejder/Library/CloudStorage/OneDrive-AlrowMedia/Dokumenter/GitHub/FV26/.venv/lib/python3.13/site-packages (1.11.0)

[notice] A new release of pip is available: 25.2 -> 26.0.1
[notice] To update, run: pip install --upgrade pip

In [20]:
folder = "../data/resultater_2022/raw"

In [21]:
# load in all the csv files in the folder and concatenate them into one dataframe

df = pd.DataFrame() # create an empty dataframe to hold the results

for file in os.listdir(folder):
    if file.endswith(".csv"):
        df = pd.read_csv(os.path.join(folder, file), sep=";")
        df['storkreds'] = file.split("_")[2] # extract storkreds from filename and add it as a column
        # remove .csv from storkreds
        df['storkreds'] = df['storkreds'].str.replace(".csv", "")
        if "resultater_2022" in locals():
            resultater_2022 = pd.concat([resultater_2022, df], ignore_index=True)
        else:
            resultater_2022 = df

In [22]:
resultater_2022

,Opstillingskreds,Afstemningsområde,Partibogstav,Partinavn,Navn,Stemmetal,storkreds,storkreds_dagi,opstillingskreds_dagi
0,Frederikshavn,1. Skagen,A,Socialdemokratiet,Partiliste,409,Nordjyllands Storkreds,10.0,403591.0
1,Frederikshavn,1. Skagen,A,Socialdemokratiet,Bjarne Laustsen,506,Nordjyllands Storkreds,10.0,403591.0
2,Frederikshavn,1. Skagen,A,Socialdemokratiet,Mette Frederiksen,926,Nordjyllands Storkreds,10.0,403591.0
3,Frederikshavn,1. Skagen,A,Socialdemokratiet,Ane Halsboe-Jørgensen,52,Nordjyllands Storkreds,10.0,403591.0
4,Frederikshavn,1. Skagen,A,Socialdemokratiet,Per Husted,1,Nordjyllands Storkreds,10.0,403591.0
...,...,...,...,...,...,...,...,...,...
337927,Hedenstedkredsen,25. Hjortsvang,Å,Alternativet,Mads Damgaard Mortensen,0,Østjyllands Storkreds,NaN,NaN
337928,Hedenstedkredsen,25. Hjortsvang,Å,Alternativet,Thomas Due Nielsen,0,Østjyllands Storkreds,NaN,NaN
337929,Hedenstedkredsen,25. Hjortsvang,Å,Alternativet,Thor Clasen Jonasen,0,Østjyllands Storkreds,NaN,NaN
337930,Hedenstedkredsen,25. Hjortsvang,(Uden for parti),(Uden for parti),Jesper Antonsen,0,Østjyllands Storkreds,NaN,NaN
337931,Hedenstedkredsen,25. Hjortsvang,(Uden for parti),(Uden for parti),Chresten H. Ibsen,0,Østjyllands Storkreds,NaN,NaN

In [23]:
resultater_2022['Opstillingskreds'].value_counts()

Opstillingskreds
Haderslev            4862
Haderslevkredsen     4862
Kalundborg           4230
Kalundborgkredsen    4230
Brønderslev          3861
                     ...
Slotskredsen          580
Aakirkeby             315
Aakirkebykredsen      315
Rønne                 135
Rønnekredsen          135
Name: count, Length: 184, dtype: int64

In [24]:
resultater_2022

,Opstillingskreds,Afstemningsområde,Partibogstav,Partinavn,Navn,Stemmetal,storkreds,storkreds_dagi,opstillingskreds_dagi
0,Frederikshavn,1. Skagen,A,Socialdemokratiet,Partiliste,409,Nordjyllands Storkreds,10.0,403591.0
1,Frederikshavn,1. Skagen,A,Socialdemokratiet,Bjarne Laustsen,506,Nordjyllands Storkreds,10.0,403591.0
2,Frederikshavn,1. Skagen,A,Socialdemokratiet,Mette Frederiksen,926,Nordjyllands Storkreds,10.0,403591.0
3,Frederikshavn,1. Skagen,A,Socialdemokratiet,Ane Halsboe-Jørgensen,52,Nordjyllands Storkreds,10.0,403591.0
4,Frederikshavn,1. Skagen,A,Socialdemokratiet,Per Husted,1,Nordjyllands Storkreds,10.0,403591.0
...,...,...,...,...,...,...,...,...,...
337927,Hedenstedkredsen,25. Hjortsvang,Å,Alternativet,Mads Damgaard Mortensen,0,Østjyllands Storkreds,NaN,NaN
337928,Hedenstedkredsen,25. Hjortsvang,Å,Alternativet,Thomas Due Nielsen,0,Østjyllands Storkreds,NaN,NaN
337929,Hedenstedkredsen,25. Hjortsvang,Å,Alternativet,Thor Clasen Jonasen,0,Østjyllands Storkreds,NaN,NaN
337930,Hedenstedkredsen,25. Hjortsvang,(Uden for parti),(Uden for parti),Jesper Antonsen,0,Østjyllands Storkreds,NaN,NaN
337931,Hedenstedkredsen,25. Hjortsvang,(Uden for parti),(Uden for parti),Chresten H. Ibsen,0,Østjyllands Storkreds,NaN,NaN

In [25]:
storkreds_dagi = {
    "Københavns Storkreds": 1,
    "Københavns Omegns Storkreds": 2,
    "Nordsjællands Storkreds": 3,
    "Bornholms Storkreds": 4,
    "Sjællands Storkreds": 5,
    "Fyns Storkreds": 6,
    "Sydjyllands Storkreds": 7,
    "Østjyllands Storkreds": 8,
    "Vestjyllands Storkreds": 9,
    "Nordjyllands Storkreds": 10,
}

In [26]:
opstillingskredse_dagi = {
    "Frederikshavn": 403591,
    "Hjørring": 403584,
    "Brønderslev": 403592,
    "Thisted": 403593,
    "Himmerland": 403594,
    "Mariagerfjord": 403583,
    "Aalborg Øst": 403596,
    "Aalborg Vest": 403595,
    "Aalborg Nord": 403599,
    "Helsingør": 403552,
    "Fredensborg": 403554,
    "Hillerød": 403555,
    "Frederikssund": 403556,
    "Egedal": 403553,
    "Rudersdal": 403577,
    "Struer": 403588,
    "Skive": 403582,
    "Viborg Vest": 403597,
    "Viborg Øst": 403601,
    "Silkeborg Nord": 403605,
    "Silkeborg Syd": 403606,
    "Ikast": 403600,
    "Herning Syd": 403590,
    "Herning Nord": 403589,
    "Holstebro": 403579,
    "Ringkøbing": 403580,
    "Lolland": 403639,
    "Guldborgsund": 403638,
    "Vordingborg": 403636,
    "Næstved": 403635,
    "Faxe": 403637,
    "Køge": 403633,
    "Greve": 403634,
    "Roskilde": 403629,
    "Holbæk": 403628,
    "Kalundborg": 403631,
    "Ringsted": 403632,
    "Slagelse": 403630,
    "Sønderborg": 403618,
    "Aabenraa": 403621,
    "Tønder": 403619,
    "Esbjerg By": 403625,
    "Esbjerg Omegns": 403624,
    "Varde": 403620,
    "Vejen": 403623,
    "Vejle Nord": 403641,
    "Vejle Syd": 403640,
    "Fredericia": 403622,
    "Kolding Nord": 403626,
    "Kolding Syd": 403627,
    "Haderslev": 403617,
    "Odense Øst": 403610,
    "Odense Vest": 403612,
    "Odense Syd": 403611,
    "Assens": 403609,
    "Middelfart": 403613,
    "Nyborg": 403614,
    "Svendborg": 403615,
    "Faaborg": 403616,
    "Gentofte": 403558,
    "Lyngby": 403557,
    "Gladsaxe": 403571,
    "Rødovre": 403562,
    "Hvidovre": 403572,
    "Brøndby": 403560,
    "Taastrup": 403561,
    "Ballerup": 403559,
    "Rønne": 403550,
    "Aakirkeby": 403551,
    "Østerbro": 403564,
    "Sundbyvester": 403565,
    "Indre By": 403573,
    "Sundbyøster": 403566,
    "Nørrebro": 403567,
    "Bispebjerg": 403568,
    "Brønshøj": 403575,
    "Valby": 403576,
    "Vesterbro": 403574,
    "Falkoner": 403570,
    "Slots": 403569,
    "Tårnby": 403563,
    "Aarhus Syd": 403587,
    "Aarhus Vest": 403608,
    "Aarhus Nord": 403607,
    "Aarhus Øst": 403604,
    "Djurs": 403602,
    "Randers Nord": 403586,
    "Randers Syd": 403598,
    "Favrskov": 403603,
    "Skanderborg": 403585,
    "Horsens": 403578,
    "Hedensted": 403581
}

In [27]:
# add the storkreds and opstillingskreds numbers to the dataframe
resultater_2022['storkreds_dagi'] = resultater_2022['storkreds'].map(storkreds_dagi)
resultater_2022['Opstillingskreds'] = resultater_2022['Opstillingskreds'].str.replace("kredsen", "")
resultater_2022['opstillingskreds_dagi'] = resultater_2022['Opstillingskreds'].map(opstillingskredse_dagi)

In [28]:
# standardiser partibogstaver, så A bliver til S, og så videre
bogstav_to_bogstav = {
    "A": "S",
    "B": "R",
    "C": "K",
    "D": "NB",
    "F": "SF",
    "H": "BP",
    "I": "LA",
    "M": "M",
    "O": "DF",
    "Q": "FG",
    "V": "V",
    "Æ": "DD",
    "Ø": "EL",
    "Å": "ALT",
    "(Uden for parti)": "UP",
}

In [29]:
resultater_2022

,Opstillingskreds,Afstemningsområde,Partibogstav,Partinavn,Navn,Stemmetal,storkreds,storkreds_dagi,opstillingskreds_dagi
0,Frederikshavn,1. Skagen,A,Socialdemokratiet,Partiliste,409,Nordjyllands Storkreds,10,403591
1,Frederikshavn,1. Skagen,A,Socialdemokratiet,Bjarne Laustsen,506,Nordjyllands Storkreds,10,403591
2,Frederikshavn,1. Skagen,A,Socialdemokratiet,Mette Frederiksen,926,Nordjyllands Storkreds,10,403591
3,Frederikshavn,1. Skagen,A,Socialdemokratiet,Ane Halsboe-Jørgensen,52,Nordjyllands Storkreds,10,403591
4,Frederikshavn,1. Skagen,A,Socialdemokratiet,Per Husted,1,Nordjyllands Storkreds,10,403591
...,...,...,...,...,...,...,...,...,...
337927,Hedensted,25. Hjortsvang,Å,Alternativet,Mads Damgaard Mortensen,0,Østjyllands Storkreds,8,403581
337928,Hedensted,25. Hjortsvang,Å,Alternativet,Thomas Due Nielsen,0,Østjyllands Storkreds,8,403581
337929,Hedensted,25. Hjortsvang,Å,Alternativet,Thor Clasen Jonasen,0,Østjyllands Storkreds,8,403581
337930,Hedensted,25. Hjortsvang,(Uden for parti),(Uden for parti),Jesper Antonsen,0,Østjyllands Storkreds,8,403581
337931,Hedensted,25. Hjortsvang,(Uden for parti),(Uden for parti),Chresten H. Ibsen,0,Østjyllands Storkreds,8,403581

In [30]:
valgsted_resultater = (
    resultater_2022.groupby(["Afstemningsområde", "Partibogstav"])["Stemmetal"].sum().reset_index()
)

valgsted_resultater['procent_22'] = (round(
    valgsted_resultater['Stemmetal']
    / valgsted_resultater.groupby('Afstemningsområde')['Stemmetal'].transform('sum')
    * 100
,1))

In [31]:
storkreds_resultater = (
    resultater_2022
    .groupby(['storkreds_dagi', 'storkreds', 'Partibogstav'])
    .agg({"Stemmetal": "sum"})
    .reset_index()
)

storkreds_resultater['procent_22'] = (round(
    storkreds_resultater['Stemmetal']
    / storkreds_resultater.groupby('storkreds_dagi')['Stemmetal'].transform('sum')
    * 100
,1))

In [32]:
opstillingskreds_resultater = (
    resultater_2022
    .groupby(['opstillingskreds_dagi', 'Opstillingskreds', 'Partibogstav'])
    .agg({"Stemmetal": "sum"})
    .reset_index()
)

opstillingskreds_resultater['procent_22'] = (round(
    opstillingskreds_resultater['Stemmetal']
    / opstillingskreds_resultater.groupby('opstillingskreds_dagi')['Stemmetal'].transform('sum')
    * 100
,1))

In [33]:
nationalt_resultater = (
    resultater_2022
    .groupby('Partibogstav')
    .agg({"Stemmetal": "sum"})
    .reset_index()
)

nationalt_resultater['procent_22'] = (round(
    nationalt_resultater['Stemmetal']
    / nationalt_resultater['Stemmetal'].sum()
    * 100
,1))

In [34]:
# remove K from all files
valgsted_resultater = valgsted_resultater[valgsted_resultater["Partibogstav"] != "K"]
storkreds_resultater = storkreds_resultater[storkreds_resultater["Partibogstav"] != "K"]
opstillingskreds_resultater = opstillingskreds_resultater[opstillingskreds_resultater["Partibogstav"] != "K"]
nationalt_resultater = nationalt_resultater[nationalt_resultater["Partibogstav"] != "K"]

In [35]:
# standardiser partibogstaver
for bogstav, standard in bogstav_to_bogstav.items():
    valgsted_resultater.loc[valgsted_resultater['Partibogstav'] == bogstav, 'Partibogstav'] = standard
    storkreds_resultater.loc[storkreds_resultater['Partibogstav'] == bogstav, 'Partibogstav'] = standard
    opstillingskreds_resultater.loc[opstillingskreds_resultater['Partibogstav'] == bogstav, 'Partibogstav'] = standard
    nationalt_resultater.loc[nationalt_resultater['Partibogstav'] == bogstav, 'Partibogstav'] = standard

In [36]:
valgsted_resultater.to_csv("../data/resultater_2022/processed/afstemningssted_resultater.csv", index=False)
storkreds_resultater.to_csv("../data/resultater_2022/processed/storkreds_resultater.csv", index=False)
opstillingskreds_resultater.to_csv("../data/resultater_2022/processed/opstillingskreds_resultater.csv", index=False)
nationalt_resultater.to_csv("../data/resultater_2022/processed/nationalt_resultater.csv", index=False)